name: LootBalloon
version: 1.0.4
main: com.xbaimiao.lootballoon.LootBalloon
authors:
  - xbaimiao
depend:
  - MythicMobs
  - ItemsAdder
api-version: "1.13"
folia-supported: true
update-info: "优化Roll逻辑"
