name: LootBalloon
version: 1.0.3
main: com.xbaimiao.lootballoon.LootBalloon
authors:
  - xbaimiao
depend:
  - MythicMobs
  - ItemsAdder
api-version: "1.13"
folia-supported: true
update-info: "更新气球刷新坐标暴露和点击传送功能（可选开启）"
